// <auto-generated />
using System;
using DoAnTotNghiep.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnTotNghiep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227080650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnTotNghiep.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("CoverLetter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cover_letter")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("CvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cv_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Location")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resume_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("SeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seeker_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("ApplicationId")
                        .HasName("PK_applications_application_id");

                    b.HasIndex(new[] { "ApplicationId" }, "applications$application_id")
                        .IsUnique();

                    b.HasIndex(new[] { "CvId" }, "cv_id");

                    b.HasIndex(new[] { "JobId" }, "job_id");

                    b.HasIndex(new[] { "ResumeId" }, "resume_id");

                    b.HasIndex(new[] { "SeekerId" }, "seeker_id");

                    b.ToTable("applications", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.ArticleCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("CategoryId")
                        .HasName("PK_article_categories_category_id");

                    b.HasIndex(new[] { "CategoryId" }, "article_categories$category_id")
                        .IsUnique();

                    b.ToTable("article_categories", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.ArticleCategoryMap", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.HasKey("ArticleId", "CategoryId")
                        .HasName("PK_article_category_map_article_id");

                    b.ToTable("article_category_map", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.ArticleTag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("TagId")
                        .HasName("PK_article_tags_tag_id");

                    b.HasIndex(new[] { "Name" }, "article_tags$name")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.HasIndex(new[] { "TagId" }, "article_tags$tag_id")
                        .IsUnique();

                    b.ToTable("article_tags", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.ArticleTagMap", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("ArticleId", "TagId")
                        .HasName("PK_article_tag_map_article_id");

                    b.ToTable("article_tag_map", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.CareerArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int?>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("author_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Content")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Slug")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("ArticleId")
                        .HasName("PK_career_articles_article_id");

                    b.HasIndex(new[] { "ArticleId" }, "career_articles$article_id")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "career_articles$slug")
                        .IsUnique()
                        .HasFilter("[slug] IS NOT NULL");

                    b.ToTable("career_articles", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.CvUpload", b =>
                {
                    b.Property<int>("CvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cv_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CvId"));

                    b.Property<string>("FilePath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_path")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("FileType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_type")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("SeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seeker_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("CvId")
                        .HasName("PK_cv_uploads_cv_id");

                    b.HasIndex(new[] { "CvId" }, "cv_uploads$cv_id")
                        .IsUnique();

                    b.HasIndex(new[] { "SeekerId" }, "seeker_id");

                    b.ToTable("cv_uploads", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerId"));

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("CompanyName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("company_name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("CompanySize")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("company_size")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("CompanyWebsite")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("company_website")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("industry_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Logo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("logo")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EmployerId")
                        .HasName("PK_employers_employer_id");

                    b.HasIndex(new[] { "EmployerId" }, "employers$employer_id")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "employers$user_id")
                        .IsUnique();

                    b.HasIndex(new[] { "IndustryId" }, "industry_id");

                    b.ToTable("employers", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EmployerPackage", b =>
                {
                    b.Property<int>("EmployerPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employer_package_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerPackageId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("employer_id");

                    b.Property<DateTime>("EndDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("end_date");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<DateTime>("StartDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("EmployerPackageId")
                        .HasName("PK_employer_packages_employer_package_id");

                    b.HasIndex(new[] { "EmployerId" }, "employer_id");

                    b.HasIndex(new[] { "PackageId" }, "package_id");

                    b.ToTable("employer_packages", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.EmployerReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("comment")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employer_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<short?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("SeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seeker_id")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("ReviewId")
                        .HasName("PK_employer_reviews_review_id");

                    b.HasIndex(new[] { "EmployerId" }, "employer_id");

                    b.HasIndex(new[] { "ReviewId" }, "employer_reviews$review_id")
                        .IsUnique();

                    b.HasIndex(new[] { "SeekerId" }, "seeker_id");

                    b.ToTable("employer_reviews", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Industry", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("industry_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryId"));

                    b.Property<string>("NameIndustry")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name_industry")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("IndustryId")
                        .HasName("PK_industry_industry_id");

                    b.HasIndex(new[] { "IndustryId" }, "industry$industry_id")
                        .IsUnique();

                    b.ToTable("industry", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.JobCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("CategoryId")
                        .HasName("PK_job_categories_category_id");

                    b.HasIndex(new[] { "CategoryId" }, "job_categories$category_id")
                        .IsUnique();

                    b.ToTable("job_categories", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.JobPost", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int?>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Education")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("education")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employer_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Images")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<short?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("is_approved");

                    b.Property<string>("JobType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_type")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Level")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Location")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quantity")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Requirements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("SalaryRange")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("salary_range")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<string>("WorkForm")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("work_form")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("JobId")
                        .HasName("PK_job_posts_job_id");

                    b.HasIndex(new[] { "CategoryId" }, "category_id");

                    b.HasIndex(new[] { "EmployerId" }, "employer_id");

                    b.HasIndex(new[] { "JobId" }, "job_posts$job_id")
                        .IsUnique();

                    b.ToTable("job_posts", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.JobPostCategory", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.HasKey("JobId", "CategoryId")
                        .HasName("PK_job_post_categories_job_id");

                    b.HasIndex(new[] { "CategoryId" }, "category_id");

                    b.ToTable("job_post_categories", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.JobPostFeature", b =>
                {
                    b.Property<int>("JobPostFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_post_feature_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobPostFeatureId"));

                    b.Property<DateTime>("EndDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("end_date");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("feature_type");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<DateTime>("StartDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("start_date");

                    b.HasKey("JobPostFeatureId")
                        .HasName("PK_job_post_features_job_post_feature_id");

                    b.HasIndex(new[] { "JobId" }, "job_id");

                    b.ToTable("job_post_features", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.JobSeeker", b =>
                {
                    b.Property<int>("SeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seeker_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeekerId"));

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("EducationLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("education_level")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("experience_years")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("full_name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Skills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("skills")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SeekerId")
                        .HasName("PK_job_seekers_seeker_id");

                    b.HasIndex(new[] { "SeekerId" }, "job_seekers$seeker_id")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "job_seekers$user_id")
                        .IsUnique();

                    b.ToTable("job_seekers", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<short?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("is_read")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("ReceiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("receiver_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("SenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sender_id")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("MessageId")
                        .HasName("PK_messages_message_id");

                    b.HasIndex(new[] { "MessageId" }, "messages$message_id")
                        .IsUnique();

                    b.HasIndex(new[] { "ReceiverId" }, "receiver_id");

                    b.HasIndex(new[] { "SenderId" }, "sender_id");

                    b.ToTable("messages", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<short?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_read");

                    b.Property<int?>("RelatedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("related_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK_notifications_notification_id");

                    b.HasIndex(new[] { "CreatedAt" }, "created_at");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_user_created");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "idx_user_read");

                    b.HasIndex(new[] { "IsRead" }, "is_read");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("notifications", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Resume", b =>
                {
                    b.Property<int>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resume_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResumeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Education")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("education")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("experience")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("SeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seeker_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Skills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("skills")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Summary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("ResumeId")
                        .HasName("PK_resumes_resume_id");

                    b.HasIndex(new[] { "ResumeId" }, "resumes$resume_id")
                        .IsUnique();

                    b.HasIndex(new[] { "SeekerId" }, "seeker_id");

                    b.ToTable("resumes", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.SeekerFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("comment")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employer_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<short?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("SeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seeker_id")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("FeedbackId")
                        .HasName("PK_seeker_feedback_feedback_id");

                    b.HasIndex(new[] { "EmployerId" }, "employer_id");

                    b.HasIndex(new[] { "FeedbackId" }, "seeker_feedback$feedback_id")
                        .IsUnique();

                    b.HasIndex(new[] { "SeekerId" }, "seeker_id");

                    b.ToTable("seeker_feedback", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.ServicePackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<short?>("DurationDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("duration_days")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Features")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("features")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<float?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasColumnName("price")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("PackageId")
                        .HasName("PK_service_packages_package_id");

                    b.HasIndex(new[] { "PackageId" }, "service_packages$package_id")
                        .IsUnique();

                    b.ToTable("service_packages", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("package_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("TransactionId")
                        .HasName("PK_transactions_transaction_id");

                    b.HasIndex(new[] { "TransactionId" }, "transactions$transaction_id")
                        .IsUnique();

                    b.ToTable("transactions", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.UserProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Bio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId")
                        .HasName("PK_user_profiles_profile_id");

                    b.HasIndex(new[] { "UserId" }, "user_profiles$user_id")
                        .IsUnique();

                    b.ToTable("user_profiles", "tuyendung");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("normal")
                        .HasColumnName("account_type");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("facebook_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IdentityUserId");

                    b.Property<short?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK_users_user_id");

                    b.ToTable("users", "tuyendung");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Employer", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.JobPost", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.JobCategory", "Category")
                        .WithMany("JobPosts")
                        .HasForeignKey("CategoryId");

                    b.HasOne("DoAnTotNghiep.Models.Employer", "Employer")
                        .WithMany("JobPosts")
                        .HasForeignKey("EmployerId");

                    b.Navigation("Category");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnTotNghiep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoAnTotNghiep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.Employer", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("DoAnTotNghiep.Models.JobCategory", b =>
                {
                    b.Navigation("JobPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
